name: Python CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Upgrade pip
        run: python3 -m pip install --upgrade pip

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Install nhlpy from GitHub
        run: pip install git+https://github.com/0xalexdelgado/nhlpy.git@master

      - name: Debug NHLClient
        run: python3 -c "from nhlpy import NHLClient; print(NHLClient)"

      - name: Run Ingestor (dry run)
        if: success()
        run: python3 Ingestor.py