name: Python CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Upgrade pip
        run: python3 -m pip install --upgrade pip

      - name: Install dependencies
        run: |
          # Install all requirements except nhlpy
          pip install $(grep -v 'nhlpy' requirements.txt)
          # Install the GitHub version of nhlpy
          pip install --upgrade git+https://github.com/0xalexdelgado/nhlpy.git@master

      - name: Inspect nhlpy package
        run: |
          python3 -c "import nhlpy; import os; print('nhlpy installed at:', os.path.dirname(nhlpy.__file__)); print('Contents:', os.listdir(os.path.dirname(nhlpy.__file__)))"

      - name: Test NHLClient import
        run: |
          python3 -c "from nhlpy import NHLClient; print(NHLClient)"